#!/bin/bash

if [ "$1" = "clean" ]
then
    rm src/lexer.ml
    rm bin/*
    exit 0
fi

# If ocamlc is not in your PATH, put the full path here.
export OCAMLC=ocamlc
export OCAMLLEX=ocamllex

$OCAMLLEX src/lexer.mll

$OCAMLC -I bin -o bin/utils.cmi -c src/utils.mli
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/utils.cmo -c src/utils.ml
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/sha256.cmi -c src/sha256.mli
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/sha256.cmo -c src/sha256.ml
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/merkle.cmi -c src/merkle.mli
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/merkle.cmo -c src/merkle.ml
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/syntax.cmi -c src/syntax.mli
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/syntax.cmo -c src/syntax.ml
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/parser.cmi -c src/parser.mli
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/parser.cmo -c src/parser.ml
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/lexer.cmo -c src/lexer.ml
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -I bin -o bin/aimleap.cmo -c src/aimleap.ml
if [ $? -gt 0 ]
then
    exit 1
fi
$OCAMLC -o bin/aimleap unix.cma bin/utils.cmo bin/sha256.cmo bin/merkle.cmo bin/syntax.cmo bin/parser.cmo bin/lexer.cmo bin/aimleap.cmo
if [ $? -gt 0 ]
then
    exit 1
fi
